cqse/teamscale-javascript-profiler

- .idea/runConfigurations/Run_Collector.xml
- packages/teamscale-coverage-collector/CHANGELOG.md
- packages/teamscale-coverage-collector/src/main.ts
Addresses issue [TS-29616](https://cqse.atlassian.net/browse/TS-29616)
> TS-29616 Logging of HTTP Status Text

- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/src/instrumenter/Cleaner.ts
- packages/teamscale-javascript-instrumenter/test/Cleaner.test.ts
- yarn.lock
Addresses issue [TS-29293](https://cqse.atlassian.net/browse/TS-29293)
> TS-29293 Remove undesired branch counters

- .idea/runConfigurations/Instrument_casestudy_angular_hero_app.xml
- .idea/runConfigurations/Instrument_casestudy_angular_hero_app_Exclude.xml
- .idea/runConfigurations/Instrument_casestudy_angular_hero_app_Include.xml
- .idea/runConfigurations/Run_System_Test.xml
- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/package.json
- packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/TaskBuilder.ts
- test/systemtest.mjs
- yarn.lock
Addresses issue [TS-29789](https://cqse.atlassian.net/browse/TS-29789)
> TS-29789 Include/excludes not considered correctly.

- .idea/prettier.xml
- packages/teamscale-coverage-collector/src/main.ts
- packages/teamscale-coverage-collector/src/receiver/CollectingServer.ts
- packages/teamscale-coverage-collector/src/receiver/Session.ts
- packages/teamscale-coverage-collector/src/storage/DataStorage.ts
- packages/teamscale-javascript-instrumenter/src/App.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/Cleaner.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/Task.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/TaskBuilder.ts
- packages/teamscale-javascript-instrumenter/src/vaccine/Interceptor.ts
- packages/teamscale-javascript-instrumenter/src/vaccine/main.ts
- packages/teamscale-javascript-instrumenter/src/vaccine/protocol.ts
- packages/teamscale-javascript-instrumenter/test/Cleaner.test.ts
- packages/teamscale-javascript-instrumenter/test/system/inputs/angular-hero-main-es5.js
- packages/teamscale-javascript-instrumenter/test/system/inputs/plain-ts-main.js
- packages/teamscale-javascript-instrumenter/workers.d.ts
Addresses issue [TS-30067](https://cqse.atlassian.net/browse/TS-30067)
> TS-30067 Reformatting using Prettier

- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/src/App.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/Task.ts
- packages/teamscale-javascript-instrumenter/src/vaccine/worker/vaccine.worker.ts
- test/systemtest.mjs
Addresses issue [TS-30231](https://cqse.atlassian.net/browse/TS-30231)
> TS-30231 Allow for using wss://server:port/path as collector specifier.

- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/src/vaccine/Interceptor.ts
- packages/teamscale-javascript-instrumenter/src/vaccine/main.ts
- packages/teamscale-javascript-instrumenter/src/vaccine/protocol.ts
- packages/teamscale-javascript-instrumenter/src/vaccine/types.ts
- packages/teamscale-javascript-instrumenter/src/vaccine/worker/CoverageAggregator.ts
- packages/teamscale-javascript-instrumenter/src/vaccine/worker/vaccine.worker.ts
Addresses issue [TS-30343](https://cqse.atlassian.net/browse/TS-30343)
> TS-30343 Move code range lookup into the Web worker

- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/src/vaccine/worker/CachingSocket.ts
- packages/teamscale-javascript-instrumenter/src/vaccine/worker/CoverageAggregator.ts
Addresses issue [TS-30409](https://cqse.atlassian.net/browse/TS-30409)
> TS-30409 Performance-related Code Refactorings

- packages/teamscale-coverage-collector/src/receiver/Session.ts
- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
- packages/teamscale-javascript-instrumenter/src/vaccine/Interceptor.ts
- packages/teamscale-javascript-instrumenter/src/vaccine/main.ts
- packages/teamscale-javascript-instrumenter/src/vaccine/worker/CoverageAggregator.ts
- packages/teamscale-javascript-instrumenter/src/vaccine/worker/vaccine.worker.ts
Addresses issue [TS-30484](https://cqse.atlassian.net/browse/TS-30484)
> Cr/30484 Tab Crash: Coverage Interception Initialized Too Often

- .idea/misc.xml
- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/package.json
- packages/teamscale-javascript-instrumenter/src/instrumenter/Cleaner.ts
- test/systemtest.mjs
- yarn.lock
Addresses issue [TS-30662](https://cqse.atlassian.net/browse/TS-30662)
> Cr/30662 Partial Instrumentation Fix

- packages/teamscale-coverage-collector/CHANGELOG.md
- packages/teamscale-coverage-collector/package.json
- packages/teamscale-coverage-collector/src/main.ts
- packages/teamscale-coverage-collector/src/storage/DataStorage.ts
- packages/teamscale-coverage-collector/test/DataStorage.test.ts
- test/systemtest.mjs
- yarn.lock
Addresses issue [TS-30356](https://cqse.atlassian.net/browse/TS-30356)
> TS-30356: Coverage Reset after Dumping to TS or File

- architecture-decisions/0001-bundle-instrumentation.md
- architecture-decisions/README.md
Addresses issue [TS-31862](https://cqse.atlassian.net/browse/TS-31862)
> TS-31862: Architecture Decision on Bundle Instrumentation

- test/casestudies/vite-react-app/package-lock.json
- test/casestudies/vite-react-app/package.json
- test/casestudies/vite-react-ts-coverable-app/package-lock.json
- test/casestudies/vite-react-ts-coverable-app/package.json
- test/casestudies/vite-vue-ts-app/package.json
Addresses issue [TS-31864](https://cqse.atlassian.net/browse/TS-31864)
> TS-31864: Upgraded the Vite Version of the Case Studies

- packages/teamscale-coverage-collector/src/receiver/Session.ts
Addresses issue [TS-31865](https://cqse.atlassian.net/browse/TS-31865)
> TS-31865: Map Unmapped Coverage If Sourcemap Arrives

- packages/teamscale-coverage-collector/CHANGELOG.md
- packages/teamscale-coverage-collector/package.json
- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/package.json
- yarn.lock
Addresses issue [TS-33123](https://cqse.atlassian.net/browse/TS-33123)
> TS-33123 Error in 'source-map' could lead to instrumentation failures

- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/src/App.ts
- packages/teamscale-javascript-instrumenter/test/system/Instrumenter.test.ts
- packages/teamscale-javascript-instrumenter/test/unit/App.test.ts
Addresses issue [TS-33372](https://cqse.atlassian.net/browse/TS-33372)
> TS-33372 Remove string quotes from input arguments

- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/src/App.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/Task.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/TaskBuilder.ts
- packages/teamscale-javascript-instrumenter/test/system/Instrumenter.test.ts
- test/systemtest.mjs
Addresses issue [TS-30461](https://cqse.atlassian.net/browse/TS-30461)
> TS-30461 Functionality to exclude certain bundles during instrumentation

- packages/teamscale-coverage-collector/CHANGELOG.md
- packages/teamscale-coverage-collector/src/upload/ArtifactoryUpload.ts
- packages/teamscale-coverage-collector/src/upload/ProxyUpload.ts
- packages/teamscale-coverage-collector/src/upload/TeamscaleUpload.ts
- packages/teamscale-coverage-collector/src/utils/ConfigParameters.ts
Addresses issue [TS-32412](https://cqse.atlassian.net/browse/TS-32412)
> TS-32412 Support proxy servers

- .github/workflows/build-and-test.yml
- .github/workflows/release.yml
Addresses issue [TS-33480](https://cqse.atlassian.net/browse/TS-33480)
> TS-33480 Upgraded to the latest Github actions

- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/src/App.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
- packages/teamscale-javascript-instrumenter/test/system/Instrumenter.test.ts
Addresses issue [TS-XXXXX](https://cqse.atlassian.net/browse/TS-XXXXX)
> TS-33851 Enhanced argument unquoting and logging

- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/src/instrumenter/Postprocessor.ts
- packages/teamscale-javascript-instrumenter/test/unit/Postprocessor.test.ts
Addresses issue [TS-XXXXX](https://cqse.atlassian.net/browse/TS-XXXXX)
> TS-33868 Non Colliding File Identifiers

- packages/teamscale-coverage-collector/package.json
- packages/teamscale-coverage-collector/src/upload/ArtifactoryUpload.ts
- packages/teamscale-coverage-collector/src/upload/CommonUpload.ts
- packages/teamscale-coverage-collector/test/system/ArtifactoryControlServer.test.ts
- yarn.lock
axios sometimes hangs when sending streams
Addresses issue [TS-33126](https://cqse.atlassian.net/browse/TS-33126)
> TS-33126 Fix test flickering

- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/Task.ts
- packages/teamscale-javascript-instrumenter/test/unit/Task.test.ts
- test/systemtest.mjs
Addresses issue [TS-33126](https://cqse.atlassian.net/browse/TS-33126)
> TS-33126 Fix exclude pattern not applying

- packages/teamscale-javascript-instrumenter/package.json
- packages/teamscale-javascript-instrumenter/src/instrumenter/Postprocessor.ts
- yarn.lock
Addresses issue [TS-34618](https://cqse.atlassian.net/browse/TS-34618)
> TS-34618 Ensure that the babel versions are in sync

- .github/workflows/build-and-test.yml
- .idea/misc.xml
- packages/cqse-commons/package.json
- packages/teamscale-coverage-collector/package.json
- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/package.json
Addresses issue [TS-35397](https://cqse.atlassian.net/browse/TS-35397)
> TS-35397 use pnpm publish

- README.md
Addresses issue [TS-35446](https://cqse.atlassian.net/browse/TS-35446)
> TS-35446 Document known limitations

- test/casestudies/vite-react-app/package-lock.json
- test/casestudies/vite-react-app/package.json
- test/casestudies/vite-react-ts-coverable-app/package-lock.json
- test/casestudies/vite-react-ts-coverable-app/package.json
- test/casestudies/vite-vue-ts-app/package-lock.json
- test/casestudies/vite-vue-ts-app/package.json
> TS-0 Dependency updates (Vite in case studies)

- packages/teamscale-javascript-instrumenter/CHANGELOG.md
- packages/teamscale-javascript-instrumenter/src/App.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/Instrumenter.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/Task.ts
- packages/teamscale-javascript-instrumenter/src/instrumenter/TaskBuilder.ts
- packages/teamscale-javascript-instrumenter/src/main.ts
- packages/teamscale-javascript-instrumenter/test/system/Instrumenter.test.ts
- packages/teamscale-javascript-instrumenter/test/unit/Task.test.ts
- test/casestudies/vite-vue-ts-app/package-lock.json
- test/casestudies/vite-vue-ts-app/package.json
- test/casestudies/vite-vue-ts-app/vite.config.ts
Addresses issue [TS-37163](https://cqse.atlassian.net/browse/TS-37163)
> TS-37163 Added statistics on the matching of origin patterns.

- packages/teamscale-coverage-collector/CHANGELOG.md
- packages/teamscale-coverage-collector/src/App.ts
- packages/teamscale-coverage-collector/src/receiver/CollectingServer.ts
Addresses issue [TS-37626](https://cqse.atlassian.net/browse/TS-37626)
> TS-37626 Stats on the message received at the collector added

- CONTRIBUTING.md
- README.md
Addresses issue [TS-37537](https://cqse.atlassian.net/browse/TS-37537)
> TS-37537 Developer guideline added

- test/scripts/grafana_profile_testing.sh
- test/scripts/profile_instrumentation.sh
- test/scripts/profile_testing.sh
- test/scripts/testing_commons.sh.inc
- test/systemtest.mjs
Addresses issue [TS-38472](https://cqse.atlassian.net/browse/TS-38472)
> TS-38472 Increased robustness of the system tests
